### ISSUE TITLE
Missing day01 solution using Tailspin

### ISSUE THREAD

**Issue by Kantis** [tobega/aoc2021#1]
Hello! A common acquaintance of ours had me dive into Tailspin to solve day01 and now I'm looking for a better solution than what I managed to come up with ;) 

Any feedback? :) 

```
composer number
    <INT>
end number

processor Increments
    @: {
        count: -1"1",
        prev: 0"1"
    };

    sink accumulate
        when <?($ <$@Increments.prev~..>)> do @Increments.count: $@Increments.count + 1;
        @Increments.prev: $;
        otherwise 
        @Increments.prev: $;
    end accumulate

    source result
      $@Increments.count !
    end result
end Increments

$IN::lines -> number -> ..=Increments -> !OUT::write
```

Still struggling with part 2 as well.. Ideally I would like to figure out a way to transform the stream of values into a stream of arrays by windowing, but the syntax eludes me. 😬 

Something like 
```
templates window
   <> $(i-1..i+1)!
end window
```

**Comment by tobega** [comment]
That's really cool! I like your solution to part1, that's one of the three options I was thinking about (haven't gotten around to coding them yet)

You could do similar for part2, but just collect an array of window-sums.

Otherwise, the syntax for the window `$(i-1..i+1)` is fine, the only problem is getting the i. One way to do it might be:
```
def input: [$IN::lines -> number];
1..$input::length-2 -> \($input($..$+2) ... -> ..=Sum&{of: :()} ! \) -> ..=Increments
```

**Comment by Kantis** [comment]
Thanks for the suggestion! `def` really helped out :) I tweaked the solution a bit, to support a N-sized window

```
composer number
    <INT>
end number

processor Increments
    @: {
        count: -1"1",
        prev: 0"1"
    };

    sink accumulate
        when <?($ <$@Increments.prev~..>)> do @Increments.count: $@Increments.count + 1;
        @Increments.prev: $;
        otherwise 
        @Increments.prev: $;
    end accumulate

    source result
      $@Increments.count !
    end result
end Increments

def input: [$IN::lines -> number];

templates windowed&{windowSize:}
    $input($..$+$windowSize) ... -> ..=Sum&{of: :()} !
end windowed

def window: 2;
1..$input::length - $window -> windowed&{windowSize: $window} -> ..=Increments -> !OUT::write
```

I'll definitely give it another go tomorrow 😄
